#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SAMU")]
	public partial class SAMUDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertOcorrencia(Ocorrencia instance);
    partial void UpdateOcorrencia(Ocorrencia instance);
    partial void DeleteOcorrencia(Ocorrencia instance);
    #endregion
		
		public SAMUDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SAMUConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SAMUDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAMUDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAMUDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAMUDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Ocorrencia> Ocorrencias
		{
			get
			{
				return this.GetTable<Ocorrencia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _cpf;
		
		private string _senha;
		
		private EntitySet<Ocorrencia> _Ocorrencias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    #endregion
		
		public Usuario()
		{
			this._Ocorrencias = new EntitySet<Ocorrencia>(new Action<Ocorrencia>(this.attach_Ocorrencias), new Action<Ocorrencia>(this.detach_Ocorrencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(MAX)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="VarChar(MAX)")]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(MAX)")]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Ocorrencia", Storage="_Ocorrencias", ThisKey="id", OtherKey="usuario_id")]
		public EntitySet<Ocorrencia> Ocorrencias
		{
			get
			{
				return this._Ocorrencias;
			}
			set
			{
				this._Ocorrencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ocorrencias(Ocorrencia entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Ocorrencias(Ocorrencia entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ocorrencia")]
	public partial class Ocorrencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _usuario_id;
		
		private string _tipo;
		
		private string _nomeSolicitante;
		
		private string _nomeVitima;
		
		private System.Nullable<int> _quantidadeVitimas;
		
		private string _endereco;
		
		private string _cep;
		
		private string _informacaoAdicional;
		
		private string _situacao;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onusuario_idChanging(System.Nullable<int> value);
    partial void Onusuario_idChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OnnomeSolicitanteChanging(string value);
    partial void OnnomeSolicitanteChanged();
    partial void OnnomeVitimaChanging(string value);
    partial void OnnomeVitimaChanged();
    partial void OnquantidadeVitimasChanging(System.Nullable<int> value);
    partial void OnquantidadeVitimasChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OncepChanging(string value);
    partial void OncepChanged();
    partial void OninformacaoAdicionalChanging(string value);
    partial void OninformacaoAdicionalChanged();
    partial void OnsituacaoChanging(string value);
    partial void OnsituacaoChanged();
    #endregion
		
		public Ocorrencia()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int")]
		public System.Nullable<int> usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(MAX)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeSolicitante", DbType="VarChar(MAX)")]
		public string nomeSolicitante
		{
			get
			{
				return this._nomeSolicitante;
			}
			set
			{
				if ((this._nomeSolicitante != value))
				{
					this.OnnomeSolicitanteChanging(value);
					this.SendPropertyChanging();
					this._nomeSolicitante = value;
					this.SendPropertyChanged("nomeSolicitante");
					this.OnnomeSolicitanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeVitima", DbType="VarChar(MAX)")]
		public string nomeVitima
		{
			get
			{
				return this._nomeVitima;
			}
			set
			{
				if ((this._nomeVitima != value))
				{
					this.OnnomeVitimaChanging(value);
					this.SendPropertyChanging();
					this._nomeVitima = value;
					this.SendPropertyChanged("nomeVitima");
					this.OnnomeVitimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidadeVitimas", DbType="Int")]
		public System.Nullable<int> quantidadeVitimas
		{
			get
			{
				return this._quantidadeVitimas;
			}
			set
			{
				if ((this._quantidadeVitimas != value))
				{
					this.OnquantidadeVitimasChanging(value);
					this.SendPropertyChanging();
					this._quantidadeVitimas = value;
					this.SendPropertyChanged("quantidadeVitimas");
					this.OnquantidadeVitimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="VarChar(MAX)")]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cep", DbType="VarChar(MAX)")]
		public string cep
		{
			get
			{
				return this._cep;
			}
			set
			{
				if ((this._cep != value))
				{
					this.OncepChanging(value);
					this.SendPropertyChanging();
					this._cep = value;
					this.SendPropertyChanged("cep");
					this.OncepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_informacaoAdicional", DbType="VarChar(MAX)")]
		public string informacaoAdicional
		{
			get
			{
				return this._informacaoAdicional;
			}
			set
			{
				if ((this._informacaoAdicional != value))
				{
					this.OninformacaoAdicionalChanging(value);
					this.SendPropertyChanging();
					this._informacaoAdicional = value;
					this.SendPropertyChanged("informacaoAdicional");
					this.OninformacaoAdicionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situacao", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string situacao
		{
			get
			{
				return this._situacao;
			}
			set
			{
				if ((this._situacao != value))
				{
					this.OnsituacaoChanging(value);
					this.SendPropertyChanging();
					this._situacao = value;
					this.SendPropertyChanged("situacao");
					this.OnsituacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Ocorrencia", Storage="_Usuario", ThisKey="usuario_id", OtherKey="id", IsForeignKey=true)]
		internal Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Ocorrencias.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Ocorrencias.Add(this);
						this._usuario_id = value.id;
					}
					else
					{
						this._usuario_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
